inews/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import *
from django.conf import settings
import django.views
import django.contrib.auth.urls
from django.contrib.sitemaps.views import sitemap as s
from news import views
from django.contrib.sitemaps import GenericSitemap
from news.models import news
from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import views as v
from django.views import static as ds
info_dict = {
    'queryset': news.objects.all(),
    'date_field': 'date',
}

sitemap={'news': GenericSitemap(info_dict, priority=0.6,changefreq = 'daily')}
urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('mdeditor/', include('mdeditor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml/', s, {'sitemaps': sitemap},name='django.contrib.sitemaps.views.sitemap'),
    path('sitemap-<int:section>\.xml', v.sitemap, {'sitemaps': sitemap},name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG: 
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r'^media/(?P<path>.*)$', 
           django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),   
            url(r'^static/(?P<path>.*)$',
          django.views.static.serve,{'document_root':settings.STATIC_ROOT})]
    
handler404 = views.page_not_found
handler500 = views.server_error

news/urls.py
'''
Created on 2019年10月28日

@author: asus
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import feeds
from django.contrib.auth import views as auth_views
app_name='news'
urlpatterns = [
    path('', views.index, name='index'),
    path('sign_up/',views.sign_up.as_view(),name='signUp'),
    path('login/',auth_views.LoginView.as_view(template_name='base.html',extra_context = {'type':'login'}),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='base.html',extra_context = {'type':'logout'}),name='logout'),
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='base.html',extra_context = {'type':'login'}),name='change_password'),
    path('<int:news_id>/',views.detail,name="detail"),
    path('writer/',views.write,name="writer"),
    path('loadmore/', views.loadmore, name='loadmore'),
    path('sendEmail/',views.sendemail,name='email'),
    path('rss/',feeds.LatestNewsFeed(),name='rss'),
    path('user/<int:user_id>',views.pesonal,name='user'),
    path('uploadimg/',views.uploadimg,name="upload"),
    path('contact/',views.contact,name="contact"),
    
    ]

news/models.py
from django.db import models
from mdeditor.fields import MDTextField
from django.conf import settings
from django.utils import timezone
from builtins import str
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.urls import reverse
# Create your models here.


class writer(models.Model):
    writer_name=models.CharField(max_length=50,primary_key=True,verbose_name="name")
    text=models.CharField(max_length=200)
    password=models.CharField(max_length=20)
    activate_choice=((0,'false'),(1,'true'))
    is_active=models.IntegerField(default=0,choices=activate_choice)
    def __str__(self):
        return self.writer_name
    def text(self):
        return self.text
class news_user(User):
    introduce=models.CharField(max_length=200)
    nick_name=models.CharField(max_length=20)
    verify_code=models.CharField(max_length=10)
    head_img = models.CharField(max_length=100)
    bg_img=models.CharField(max_length=100)
    def __str__(self):
        
        return self.nick_name

class news(models.Model):
    style_chioces=(('科技','tech'),('时政','political'),('经济','ecomony'),('军事','military'))
    style=models.CharField(max_length=6,choices=style_chioces)
    news_title = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now=True)
    text=MDTextField(max_length=5000)
    writer=models.ForeignKey(writer,on_delete=models.CASCADE)
    '''author = models.ForeignKey(
        news_user,
        on_delete=models.CASCADE,
        
    )'''
    def __str__(self):
        return self.news_title
    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'news_id': self.id})
    
class video(models.Model):
    video_path=models.FileField(upload_to=settings.FILE_URL,verbose_name="视频")
    name=models.CharField(max_length=50,default=timezone.now)
    host=models.ForeignKey(news,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.video_path)

class img(models.Model):
    position=models.CharField(max_length=50)
    host=models.ForeignKey(news,on_delete=models.CASCADE)
    def __str__(self):
        return self.position


    

news/forms.py
from django.contrib.auth.forms import UserCreationForm as user
from django import forms
from django.utils.translation import gettext, gettext_lazy as _
class userForm(user):
    verify_code=forms.CharField(
        label=_("verify_code"),
        strip=False,
        widget=forms.TextInput,
    )
    email = forms.EmailField(label=_("Email"),max_length=254)

news/views.py
from django.shortcuts import render,get_object_or_404
from news.models import news as NEWS
from news.models import news,writer,video,news_user
from django.conf import settings
import markdown
from django.core.paginator import Paginator
from django.views.generic.edit import FormView
from django.template.context_processors import csrf
from .forms import userForm
# Create your views here.
# -*- coding: utf-8 -*-
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
import random
from django.core.mail import send_mail
import base64
import misaka
from bs4 import BeautifulSoup
import os
from builtins import list as L
def generate_verification_code_v2():
    ''' 随机生成6位的验证码 '''
    code_list = []
    for i in range(2):
        random_num = random.randint(0, 9) # 随机生成0-9的数字
        # 利用random.randint()函数生成一个随机整数a，使得65<=a<=90
        # 对应从“A”到“Z”的ASCII码
        a = random.randint(65, 90)
        b = random.randint(97, 122)
        random_uppercase_letter = chr(a)
        random_lowercase_letter = chr(b)
        code_list.append(str(random_num))
        code_list.append(random_uppercase_letter)
        code_list.append(random_lowercase_letter)
    verification_code = ''.join(code_list)
    return verification_code


def index(request):
    news_list=NEWS.objects.order_by('-date')[:20]
    img_list=[]
    is_auth=0
    for news in news_list:
        md_render = misaka.Markdown(misaka.HtmlRenderer())
        html = md_render(news.text)
        soup = BeautifulSoup(html, features='html.parser')
        img=soup.find('img')
        if img != None:
            
            img_list.append(img.get('src'))
        else:
            img_list.append('')
    zipped = zip(news_list,img_list)
    zip_list=list(zipped)
    if request.user.is_authenticated:
        user=get_object_or_404(news_user,id=request.user.id)
        is_auth=1
        context={'news_list':zip_list,'user':user,'is_auth':is_auth}
       
    else:
        context={'news_list':zip_list,'img_list':img_list,'is_auth':is_auth}
    return render(request,"index.html" ,context)
    
def detail(request,news_id):
    
    News=news.objects.get(id=news_id)
    V=video.objects.filter(host=News)
    News.text = markdown.markdown(News.text.replace("\r\n", '  \n'),
                                  extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    
    
    context={'News':News,'V':V,'MEDIA_URL':settings.MEDIA_URL}   
    return render(request, "detail.html",context)
    
def write(request):
    
    name=request.GET.get("writer_name")
    name=name.replace(" ","")
    w=writer.objects.get(writer_name=name)
    news_list=news.objects.filter(writer=w)
    text=w.text
    context={"text":text,"news_list":news_list,"writer":w}
    return render(request,"writer.html",context)    

class sign_up(FormView):
    form_class=userForm
    template_name = 'base.html'
    success_url='../login'
    extra_context = {'type':'signup'}
    def post(self, request, *args, **kwargs):
        ctx ={}
        ctx.update(csrf(request))
        form=userForm(request.POST)
        if form.is_valid():
            e = request.POST['email']
            un = request.POST['username']
            pw = request.POST['password']
            code=request.POST['code']
            user=get_object_or_404(news_user,email=e)
            if code==user.verify_code:
                user.set_password(pw)
                user.nick_name=un
                user.is_active=True
                user.save()
                group = Group.objects.get(name='reader') 
                group.user_set.add(user)
            else: 
                print()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

def sendemail(request):
    address=request.GET.get("email")
    code=generate_verification_code_v2()
    user = news_user.objects.create_user(email=address,password='wjx200022',verify_code=code)
    user.is_active=False
    res=send_mail('verify_code',code,'w13411965905@163.com',[address],fail_silently=False,)
    if res == 1:
            return render(request,'邮件发送成功')
    else:
            return render(request,'邮件发送失败')

def loadmore(request):
    type=request.GET.get('type')
    
    if type != None:
        List=NEWS.objects.filter(style=type).order_by('-date')
    else:
        List = NEWS.objects.order_by('-date')
    p=3
    limit =20
    img_list=[]
    for news in List:
        md_render = misaka.Markdown(misaka.HtmlRenderer())
        html = md_render(news.text)
        soup = BeautifulSoup(html, features='html.parser')
        img=soup.find('img')
        if img != None:
            
            img_list.append(img.get('src'))
        else:
            img_list.append('')
    zipped = zip(List,img_list)
    List=L(zipped)
    paginor = Paginator(List, limit)
    page = request.GET.get('page', p)
    item_info = paginor.page(page)
    news_list=item_info.object_list
    print(news_list)
    context = {'news_list': news_list,}
    template = 'load.html'
    return render(request, template, context)

def page_not_found(request,Exception):
    return render(request, '404.html', status=404)

@login_required
def pesonal(request,user_id):
    user=get_object_or_404(news_user,id=user_id)
    template='person.html'
    context={'user':user}
    return render(request,template,context)
        
def uploadimg(request):
  if request.method == 'POST':
    # 前端ajax请求，将图片对象、图片名称传递到了后台的views.py中；
    img = request.POST.get('imgData')
    type = request.POST.get('type')
    name= request.POST.get('imgname')
    # 再将列表合成一个字符串
    path = ''.join(name)
    print(img)
    i=img.split(',')
    img=i[1]
    url = settings.IMG_URL +path +'.jpg'
 
    img = base64.b64decode(img)
    # 将ajax传过来的图片写入到本地/static/images/....目录下。
    with open(url,'wb+') as f:
      
        f.write(img)
    user=get_object_or_404(news_user,id=request.user.id)
    # 以上步骤实现了图片的后台保存，还需要修改当前用户数据库中的头像路径。
    if type=='headimg':
        user.head_img = path
    else:
        user.bg_img=path
    user.save()
    template='blank.html'
    context={'content':'图片上传成功'}
    print("ok")
    return render(request,template,context)
# 500
def server_error(request):
    return render(request, '500.html', status=500)
def contact(request):
    template='contact.html'
    return render(request, template)

    

news/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="" />
<link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet" type="text/css" media="all">
<link href="{% static 'css/style3.css'%}" rel="stylesheet" type="text/css" media="all"/>
<link href="http://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900" rel="stylesheet">
<script type="text/javascript" src="{% static 'js/jquery-1.4.4.min.js'%}"></script>

<script>$(document).ready(function(){
  $("button#sendCode").click(function(){
     var email=document.getElementById('email').value;

    var url = window.location.pathname,
		url = "../sendEmail"
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange = function() {
		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
		alert(xmlHttp.responseText);
		}
		}
		xmlhttp.open("GET", url + "?email=" + email, true);
		xmlhttp.send(null);
  });
});</script>
</head>
<body>
<div class="signupform">
<h1>Interior Register Form</h1>
	<div class="container">
		<div class="agile_info">
			<div class="w3l_form">
				<div class="left_grid_info">
					<h3>Welcome !</h3>
					<h4>Lorem ipsum dolor sit amet, nulla consectetur adipiscing elit Sed.</h4>
					<p> Nam eleifend velit eget dolor vestibulum ornare. Vestibulum est nulla, fermentum eget euismod et, tincidunt at dui. Nulla tellus nisl, semper id justo vel, rutrum finibus risus. Cras vel auctor odio.</p>
					<ul class="social_section_1info">
						<li><a href="#" class="w3_facebook"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#" class="w3_twitter"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#" class="w3_instagram"><i class="fa fa-instagram"></i></a></li>
						<li><a href="#" class="w3_google"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#" class="w3_pinterest"><i class="fa fa-pinterest"></i></a></li>
						<li><a href="#" class="w3_vimeo"><i class="fa fa-vimeo"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="w3_info">
				<h2>{{type}}</h2>
				<p>Vestibulum est nulla, fermentum eget euismod et, tincidunt at dui dolor sit.</p>
				
						<form action="" method="post">  
    					{% csrf_token %}
    					{% for field in form %}
    					{{ field.label }}
						<div class="input-group">
							<span><i class="fa fa-user" aria-hidden="false"></i></span>
							{{ field }}{{ field.errors.0 }}
						</div>
						 {% endfor %}
							<input type="checkbox" value="remember-me" /> <h4>Send me latest updates </h4>
							{%ifequal type 'signup'%}
							<button  type="button" id="sendCode" class="btn btn-danger btn-block">send code</button > 
							{% endifequal %}     
							<button class="btn btn-danger btn-block" type="submit">{{type}}</button >                
					</form>
			</div>
			<div class="clear"></div>
			</div>
			
		</div>
		<div class="footer">

 <p>Copyright &copy; 2018.Company name All rights reserved.&#x7F51;&#x9875;&#x6A21;&#x677F;</p>
 </div>
	</div>
	</body>
</html>

news/templates/blank.html
{{content}}

news/templates/contact.html
{%load static %}
<!DOCTYPE html>
<!-- saved from url=(0032)https://www.toutiao.com/contact/ -->
<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="x-dns-prefetch-control" content="on">
		<meta name="renderer" content="webkit">
		
		<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
		<!--[if lt IE 9]>
  <p>您的浏览器版本过低，请<a href="http://browsehappy.com/">升级浏览器</a></p>
<![endif]-->
		<title>联系我们</title>
		<meta name="pathname" content="bui-vue">
		<link rel="stylesheet" href="{% static 'css/index.18b4e0d1bee51054e917f63a6904f819.css' %}">
		
	</head>

	<body>
		<div>
			<div class="header">
				<div class="topbar">
					<div class="bui-left clearfix"></div>
					<div class="bui-right">
						<ul class="user-nav-list clearfix">
							<!---->
							
							
						</ul>
					</div>
				</div>
				<div class="middlebar">
					<div class="middlebar-inner clearfix" style="width: 1120px;">
						<div class="bui-left logo-box">
							<a href="{%url 'news:index'%}" ga_event="go_home" class="logo-link"><img src="{% static 'images/logo.png'%}" class="logo"></a>
						</div>
						<ul class="bui-right doc-header-tab">
							
							<li class="doc-header-tab-item doc-header-tab-item-active">
								<a href="">联系我们</a>
							</li>
							
							
						</ul>
					</div>
				</div>
			</div>
			<div class="doc-container">
				<div class="doc-article">
					<ul id="contact" class="clearfix">
						<li class="big">
							<a href="#" target="_blank"><img src=""></a>
						</li>
						<li><span class="first">管理员微信 :</span> <span><strong><a href="#">xqahz588</a></strong></span></li>
						<li><span class="first">管理员邮箱 :</span> <span><strong><a href="#">2748708354@qq.com</a></strong></span> </li>
						</ul>
				</div>
			</div>
			<div class="footer">
			</div>
		</div>
		<script>
			

news/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>inews</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta name="keywords" content="新闻">
    <meta name="description" content="一站纵览，权威资讯">
    <meta property="fb:pages" content="855641774620029">
    <link rel="stylesheet" href="{% static 'css/style-index-min.css'%}">
    <!--[if lt IE 9]>
    
  <script src="//apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
<![endif]-->
<script type="text/javascript" src="{% static 'js/jquery-1.4.4.min.js'%}"></script>
	<script> var i = 3; var type;
	function loadmore(v) {
		debugger
		var url = window.location.pathname,
		url = "loadmore"
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange = function() {
		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
		$('.list').append(xmlhttp.responseText);
		}
		}
		if (v=== undefined){
		xmlhttp.open("GET", url + "?page=" + i, true);}
		else{xmlhttp.open("GET", url + "?page=" + i+"&type="+v, true);}
		i = i + 1;
		xmlhttp.send(null);
		};
	function reflash(v){debugger
		var url = window.location.pathname,
		url = "loadmore"
		var j=1;
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange = function() {
		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
		$('.list').html(xmlhttp.responseText);
		}
		}
		if (v=== undefined){
		xmlhttp.open("GET", url + "?page=" + j, true);}
		else{xmlhttp.open("GET", url + "?page=" +j +"&type="+v, true);}
		xmlhttp.send(null);
		} ;
	function randfresh(){};
	function political(){
		type="时政";
		reflash(type);
		
	}
	function economy(){
		type="经济";
		reflash(type);
	}
	function bug(){
		type="<class";
		reflash(type);
	}
</script>
</head>
<body style="">
     <form method="post" action="" id="form1" class="nice-validator n-default" novalidate="novalidate">
<div class="aspNetHidden">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTExNDcxMzQ3MTlkZE9KXPMZ2MaVhjTc4YqRj3QQSabFnlzkiS5XlejRUKws">
</div>

<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="7E21AFCE">
</div>
    <header id="header" class="clearfix">
  <h1>欢迎来到爱新闻^_^！</h1>

  {%ifequal is_auth 0 %}
   <span class="login_btn" style="display: inline-block;"><a href="{%url 'news:login'%}">登录/注册</a></span>
  {%else%}
   <div class="user-infos" style="display:inline-block;">
  	<a href="user/{{user.id}}">
    <img src="../img/{{user.head_img}}.jpg" alt="">
      <span class="name">{{user.username}}</span>
    </div></a>  
    <span class="login_btn" href="{% url 'news:logout'%}"style="display: inline-block;">退出</span>
   		
   {%endifequal%}
</header>
    <div id="main">
        ﻿<div id="leftSide">
  <h1>
    <img src="{%static 'images/logo.png'%}" width="100%">
  </h1>
  <ul>
    <li class="on"><a href="" typeid="100">首页</a></li>
    <li><a href="javascript:political()" typeid="124">时政</a></li>
    <li><a href="javascript:economy()" typeid="101">财经</a></li>
    <li><a href="javascript:bug()" typeid="3">bug</a></li>
    <li><a href="" typeid="20">奇闻</a></li>
    <li><a href="" typeid="105">美女</a></li>
    <li><a href="" typeid="21">游戏</a></li>
    <li><a href="" typeid="108">科技</a></li>
    <li><a href="" typeid="13">汽车</a></li>
    <li class="more"><span>更多</span>
      <div class="more-area">
        <a href="" typeid="125">视频购物</a>
      </div>
    </li>
  </ul>
</div>
        <!-- leftside end -->
        <div id="mainSide">
           <a href="#" id='top'></a>
            <!-- banner end -->
            <div class="recommend">
{% if news_list %}
	<ul class="list">
		{% for news in news_list %}
		
		<li class="clearfix">
			<div class="video-img">
			
				<a href="/{{news.0.id}}" target="_blank" title="{{ news.0.news_title}}"><img data-echo="" src="{{news.1}}"><i class="pic-tip video-tip"><span></span></i></a>
			</div>
			<div class="video-info">
				<div class="video-info-inner">
					<h3><a href="/{{news.0.id}}" target="_blank" title="{{ news.0.news_title}}">{{news.0.news_title}}</a></h3>
					<div class="video-from">
						<a href="" target="_blank" class="media-avatar"><img data-echo="" src=""></a>
						<a href="/writer?writer_name={{news.0.writer.writer_name}}" target="_blank" class="source">{{news.0.writer.writer_name}}<em class="indent-tag"></em></a>
					</div>
				</div>
			</div>
		</li>
		
		{% endfor %}
{% endif %}
		
	</ul>
	<!-- div class="loading ball-pulse" style="display:block;"--->
		<div></div>
		<div></div>
		<div></div> <a href="javascript:loadmore(type)" id="more">点击加载此处更多⋅</a>⋅<!-- /div--->
</div>
</div>
        <!-- mainSide end -->
        <div id="rightSide">
            <div class="search">
                <input type="text" placeholder="" autocomplete="off" id="N854735049407">
                <i>搜索</i>
            </div>
            <div class="pane-module">
                <div class="head">
                    热门视频
                </div>
<ul class="content video-list">
	<li class="video-item" id="tenant-box">
		<dl> <dt class="pic">             <a href="http://ent.cctv.com/special/zgmgqz/" target="_blank" class="link"> <img src="active.png">              <i class="hot-tag video-tag"></i>  </a></dt>
			<dd>
				<div class="cell">
					<a href="http://ent.cctv.com/special/zgmgqz/" target="_blank" class="link">
						<h4>“中国梦”主题新创作歌曲</h4></a>
					<p>
						<a href="http://ent.cctv.com/special/zgmgqz/" target="_blank" class="link"> <img height="18" width="18" class="pic" src="./爆米花视频--爆出精彩视界_files/active.png"><span>中国梦</span></a>
					</p>
				</div>
			</dd>
		</dl>
	</li>
	<li class="video-item">
		<dl>
			<dt class="pic">
                                                               <a href="" target="_blank" class="link"> <img data-echo="" src="./爆米花视频--爆出精彩视界_files/41810447.jpg">
                                                                <i class="hot-tag video-tag"><span>00:10</span></i>  </a></dt>
			<dd>
				<div class="cell">
					<a href="" target="_blank" class="link">
						<h4>长的漂亮懂道理也多，这样的小姐姐做女朋友肯定容易相处</h4></a>
					<p>
						<a href="" target="_blank" class="link"> <img data-echo="" height="18" width="18" class="pic" src="user_default.gif"><span>踏风尘</span><em class="indent-tag"></em></a>
					</p>
				</div>
			</dd>
		</dl>
	</li>
</ul>
            </div>
            ﻿<div class="pane-module aboutUs">
  <div class="head">关于我们</div>
  <a href="" target="_blank">关于inews</a>
  <a href="" target="_blank">联系我们</a>
  <a href="" target="_blank">友情链接</a>
  <a href="sitemap.xml/" target="_blank">网站地图</a>
</div>
<div class="pane-module link-other">
  
  <a href="http://www.12377.cn/" target="_blank" class="link-box">
    <s class="icon icon-2"></s>网上有害信息举报专区
  </a>
  <a href="http://www.bj.cyberpolice.cn/index.htm" target="_blank" class="link-box">
    <s class="icon icon-3"></s>网络110报警服务
  </a>
  <a href="http://jb.ccm.gov.cn/" target="_blank" class="link-box">
    <s class="icon icon-5"></s>12318全国文化市场举报网站
  </a>
 
  <a href="javascript:void(0)" target="_blank">Copyrihgt©2017 爱新闻版权所有</a>
</div>
        </div>
    </div>
 <div id="toolbar">
	<div class="refresh item">
	</div>
	<div class="returnToTop item"><a herf="#top" target='_self'></a>
	</div>
</div>
    </form>
    



</body><script>
$(document).scroll(function() {
if ($(document).scrollTop() >= $(document).height() - $(window).height()) {
loadmore();
}
});</script></html>

news/templates/load.html
{% if news_list %}
		{% for news in news_list %}
		
		<li class="clearfix">
			<div class="video-img">
			
				<a href="/{{news.0.id}}" target="_blank" title="{{ news.0.news_title}}"><img data-echo="" src="{{news.1}}"><i class="pic-tip video-tip"><span></span></i></a>
			</div>
			<div class="video-info">
				<div class="video-info-inner">
					<h3><a href="/{{news.0.id}}" target="_blank" title="{{ news.0.news_title}}">{{news.0.news_title}}</a></h3>
					<div class="video-from">
						<a href="" target="_blank" class="media-avatar"><img data-echo="" src=""></a>
						<a href="/writer?writer_name={{news.0.writer.writer_name}}" target="_blank" class="source">{{news.0.writer.writer_name}}<em class="indent-tag"></em></a>
					</div>
				</div>
			</div>
		</li>
		
		{% endfor %}
{% endif %}

news/templates/writer.html
{% load static%}
<!DOCTYPE html>
<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui">
		<meta name="renderer" content="webkit">

		<title>{{writer.writer_name}}</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<link rel="stylesheet" href="{% static 'css/personal.css' %}">
		<script>
			var appId = 87495;
			var baiduspider = 0;
		</script>
		
	</head>

	<body>
		<div id="main">
			<div id="leftSide">
				
			</div>
			<div id="mainSide">
				<div class="userInfos">
					<img src="" class="bg">
					<div class="details-info">
						<img src="" class="avatar">
						<div class="infos">
							<h2>
                        <span class="name">{{writer.writer_name}}</span>
                       
                      
                         <span class="from"></span>
                   
                    </h2>
							<p class="des"> {{writer.text}}</p>
						</div>
						<button class="btn">订阅</button>
						<button class="btn" rssed="0">订阅</button></div>
				</div>
				<div class="info-flow">
					<h3>TA的新闻</h3>
					<div class="result">
					{% if news_list %}
						<ul>
						 {% for news in news_list %}
							<li class="clearfix">
								<a href="/{{news.id}}" target="_blank">
									<div class="video-img"><img data-echo="" src=""><i class="pic-tip"><span></span></i></div>
									<div class="video-info">
										<div class="video-info-inner">
											<h2>{{ news.news_title }}</h2></div>
									</div>
								</a>
							</li>
						{%endfor%}
						</ul>
					{%endif%}
					</div>
				</div>
				<!-- 信息流end -->
				<div class="recommend">
					<h3>达人推荐</h3>
					<div class="list">
						<a href=""><img src="" class="pic">
							<p class="name">肥喵动物</p><em class="indent-tag"></em></a><button class="btn" data-appid="67442">订阅</button></div>
					</div>
				<!-- 达人推荐 -->
			</div>
		</div>
		<script src="{% static 'js/jquery-1.4.4.min.js' %}"></script>
	</body>

</html>